apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{"meta.helm.sh/release-name":"lxkdbm","meta.helm.sh/release-namespace":"lx-adj-dev"},"creationTimestamp":"2021-11-15T13:12:06Z","generation":3,"labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"lxkdbm","namespace":"lx-adj-dev","uid":"6fe1fa75-a309-4a21-aad3-4b312ee5c336"},"spec":{"podManagementPolicy":"OrderedReady","replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"lxkdbm"}},"serviceName":"lxkdbm-svc","template":{"metadata":{"creationTimestamp":null,"labels":{"app":"lxkdbm"}},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchLabels":{"app":"lxkdbm"}},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"args":["--config=/mms-config/local.config"],"command":["./mongodb-mms-automation-agent"],"image":"repo.primetherapeutics.com:17443/mongodb:0.7","imagePullPolicy":"IfNotPresent","name":"mongodb-db","resources":{"limits":{"cpu":"500m","memory":"15Gi"},"requests":{"cpu":"500m","memory":"15Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/mms-config","name":"lxkdbm-config"},{"mountPath":"/data","name":"lxkdbm"},{"mountPath":"/etc/ldap","name":"ldap-conf"}]}],"dnsPolicy":"ClusterFirst","hostAliases":[{"hostnames":["vwkdbm-1.vwkdbm-svc.vw-adj-dev.svc.cluster.local"],"ip":"10.217.24.177"},{"hostnames":["vwkdbm-1.vwkdbm-svc.vw-adj-dev.svc.cluster.local"],"ip":"10.217.24.177"},{"hostnames":["vwkdbm-0.vwkdbm-svc.vw-adj-dev.svc.cluster.local"],"ip":"10.217.24.179"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":1000,"runAsGroup":1000,"runAsUser":1000},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"items":[{"key":"local.config","path":"local.config"}],"name":"lxkdbm-config"},"name":"lxkdbm-config"},{"configMap":{"defaultMode":420,"items":[{"key":"ldap.conf","path":"ldap.conf"}],"name":"ldap-conf"},"name":"ldap-conf"}]}},"updateStrategy":{"rollingUpdate":{"partition":0},"type":"RollingUpdate"},"volumeClaimTemplates":[{"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"creationTimestamp":null,"name":"lxkdbm"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"60Gi"}},"storageClassName":"vsphere-local","volumeMode":"Filesystem"},"status":{"phase":"Pending"}}]},"status":{"collisionCount":0,"currentRevision":"lxkdbm-66c5dbd58","observedGeneration":3,"readyReplicas":1,"replicas":1,"updateRevision":"lxkdbm-56f944b7f"}}
      meta.helm.sh/release-name: lxkdbm
      meta.helm.sh/release-namespace: lx-adj-dev
    creationTimestamp: "2021-11-15T13:12:06Z"
    generation: 3
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:template:
            f:spec:
              f:hostAliases:
                .: {}
                k:{"ip":"10.217.24.177"}:
                  .: {}
                  f:hostnames: {}
                  f:ip: {}
                k:{"ip":"10.217.24.179"}:
                  .: {}
                  f:hostnames: {}
                  f:ip: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2021-11-15T13:12:25Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:spec:
          f:podManagementPolicy: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:serviceName: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:affinity:
                .: {}
                f:podAntiAffinity:
                  .: {}
                  f:requiredDuringSchedulingIgnoredDuringExecution: {}
              f:containers:
                k:{"name":"mongodb-db"}:
                  .: {}
                  f:args: {}
                  f:command: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/data"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/etc/ldap"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/mms-config"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext:
                .: {}
                f:fsGroup: {}
                f:runAsGroup: {}
                f:runAsUser: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"ldap-conf"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:items: {}
                    f:name: {}
                  f:name: {}
                k:{"name":"lxkdbm-config"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:items: {}
                    f:name: {}
                  f:name: {}
          f:updateStrategy:
            f:rollingUpdate:
              .: {}
              f:partition: {}
            f:type: {}
          f:volumeClaimTemplates: {}
      manager: Go-http-client
      operation: Update
      time: "2022-07-11T21:07:29Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:collisionCount: {}
          f:currentReplicas: {}
          f:currentRevision: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updateRevision: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-09-18T18:11:58Z"
    name: lxkdbm
    namespace: lx-adj-dev
    resourceVersion: "79984236"
    uid: 6fe1fa75-a309-4a21-aad3-4b312ee5c336
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: lxkdbm
    serviceName: lxkdbm-svc
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: lxkdbm
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: lxkdbm
              topologyKey: kubernetes.io/hostname
        containers:
        - args:
          - --config=/mms-config/local.config
          command:
          - ./mongodb-mms-automation-agent
          image: repo.primetherapeutics.com:17443/mongodb:0.7
          imagePullPolicy: IfNotPresent
          name: mongodb-db
          resources:
            limits:
              cpu: 500m
              memory: 15Gi
            requests:
              cpu: 500m
              memory: 15Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /mms-config
            name: lxkdbm-config
          - mountPath: /data
            name: lxkdbm
          - mountPath: /etc/ldap
            name: ldap-conf
        dnsPolicy: ClusterFirst
        hostAliases:
        - hostnames:
          - vwkdbm-1.vwkdbm-svc.vw-adj-dev.svc.cluster.local
          ip: 10.217.24.177
        - hostnames:
          - vwkdbm-0.vwkdbm-svc.vw-adj-dev.svc.cluster.local
          ip: 10.217.24.179
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: local.config
              path: local.config
            name: lxkdbm-config
          name: lxkdbm-config
        - configMap:
            defaultMode: 420
            items:
            - key: ldap.conf
              path: ldap.conf
            name: ldap-conf
          name: ldap-conf
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: lxkdbm
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 60Gi
        storageClassName: vsphere-local
        volumeMode: Filesystem
      status:
        phase: Pending
  status:
    collisionCount: 0
    currentReplicas: 1
    currentRevision: lxkdbm-56f944b7f
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updateRevision: lxkdbm-56f944b7f
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
