---
- name: Build replica-set-expose.yaml template
  hosts: localhost
  connection: local 
  tasks:
    - name: loop over template
      template:
        src: skynet/replica-set-expose.yaml.j2
        dest: skynet/replica-set-expose.yaml
