name: dns_records
on:
  workflow_dispatch:
    inputs:
      c01-replicasLX:
        type: choice
        description: 'cluster C01 LX Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
      C02-replicasLX:
        type: choice
        description: 'cluster C02 LX Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"        
      clusters_list:
        type: string
        description: 'list of clusters'
        required: true
        default: 'c01,c02'
env:
  NAMESPACES: 'dev,qa,stg'
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:
      - name: Get MongoDB Dump
        run: |
          START=0
          REQ_NUM=inputs.c01-replicasLX
          END=$(($svc_count + $REQ_NUM - 1))  
          for i in $(eval echo "{$START..$END}")
          do
          echo "i: $i"
          cat >> $GITHUB_WORKSPACE/replica-set-expose.yaml << EOF
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: lxkdbmc01-$i
            namespace: lx
          spec:
            externalTrafficPolicy: Cluster
            ports:
            - port: 27017
              protocol: TCP
              targetPort: 27017
            selector:
              statefulset.kubernetes.io/pod-name: lxkdbmc01-$i
            sessionAffinity: None
            type: LoadBalancer
          EOF
          done
          echo "contents"
          cat $GITHUB_WORKSPACE/replica-set-expose.yaml
        shell: bash
          
          
 


      
