name: dns_records
on:
  workflow_dispatch:
    inputs:
      host_name:
        type: string
        description: 'Host Name'
        required: true
        default: ''
      dns_subdomain:
        type: choice
        description: 'Sub Domain'
        required: true
        options:
         - mdb
         - pdb
      ip_address:
        type: string
        description: 'IP Address'
        required: true
        default: ''
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          path: skynet

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Run Python commands
        run: |
          pip install --upgrade pip
          python3.9 -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          
      - name: Install dependencies Including Ansible
        working-directory: env/
        run: |
          if [ -f ../skynet/requirements.txt ]; then pip install -r ../skynet/requirements.txt; fi
          ls -al ../ && pwd
          which python3 
