name: docker-execution
on:
  workflow_dispatch:
    inputs:
      docker_version:
        type: string
        description: 'Dockerfile version'
        required: true
        default: '0.6'
      release:
        type: string
        description: 'Release Name'
        required: true
        default: 'kdbm'
jobs:
  docker-execution:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    env:
      docker_version: 0.6
      release: 'kdbm'
      cluster4_5: 'f02'
      dbStorageType: 'csi-local'
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: PKS permissions     
        run: |
          docker ps