name: dns_records
on:
  workflow_dispatch:
    inputs:
      c01-replicasLX:
        type: choice
        description: 'cluster C01 LX Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
      c02-replicasLX:
        type: string
        description: 'cluster C01 LX Replicas count'
env:
  NAMESPACES: 'dev,qa,stg'
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:    
      - name: check the var status
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.c02-replicasLX == ''
        run: |
            c02-replicasLX="rahul"
            echo "c02-replicasLX=${c02-replicasLX}" >> $GITHUB_ENV

      - name: show the var output
        run: |
            echo "hi ${{ env.c02-replicasLX }}"
          
          
 


      
