name: dns_records
on:
  workflow_dispatch:
    inputs:
      Storge_size:
        type: string
        description: 'Provide the new storage size e.g: 80Gi'
        required: true
        default: '60Gi'
env:
  namespaces: |
     'dev'
     'qa'
     'stg'
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          path: skynet
          
      - name: list vars
        run: |
          echo $namespaces

      
