name: dns_records
on:
  workflow_dispatch:
    inputs:
      c01-replicasLX:
        type: choice
        description: 'cluster C01 LX Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
      c02-replicasLX:
        type: string
        description: 'cluster C01 LX Replicas count'
env:
  NAMESPACES: 'dev,qa,stg'
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:    
      - name: declare lxkdbmc02
        run: |
            if [[ -z "${{ inputs.c02-replicasLX }}" ]]; then
                c02-replicasLX="rahul"
            fi
            echo "hi: $c02-replicasLX"
        shell: bash
          
          
 


      
