name: dns_records
on:
  workflow_dispatch:
    inputs:
      Storge_size:
        type: string
        description: 'Provide the new storage size e.g: 80Gi'
        required: true
        default: '60Gi'
      days:
        type: string
        required: true
        default: '5'
        
      collections_list:
        type: string
        description: 'Enter list of collections to be excluded from mongodump separated by ",". ex: bridg-rule,age-limitation-mappings,addendum-summaries'
        required: true
        default: 'boy,mom'
env:
  NAMESPACES: 'dev,qa,stg'
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          path: skynet
          
      - name: Get MongoDB Dump
        run: |
          IFS=',' read -r -a array <<< ${{ inputs.collections_list }}
          list=(babe srini boy mama)
          function arraydiff() {
            awk 'BEGIN{RS=ORS=" "}
            {NR==FNR?a[$0]++:a[$0]--}
            END{for(k in a)if(a[k])print k}' <(echo -n "${!1}") <(echo -n "${!2}")
          }
          req_dbs=($(arraydiff list[@] array[@]))
          echo "req_dbs:" ${req_dbs[@]}
 


      
