name: dns_records
on:
  workflow_dispatch:
    inputs:
      c01-replicasLX:
        type: choice
        description: 'cluster C01 LX Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
      c02replicasLX:
        type: string
        description: 'cluster C02 LX Replicas count'
      c03replicasLX:
        type: string
        description: 'cluster C03 LX Replicas count'
env:
  c02replicasLX: ${{ inputs.c02replicasLX }}
  c03replicasLX: ${{ inputs.c03replicasLX }}
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:    
      - name: check the var status
        if: github.event.inputs.c02replicasLX == '' && github.event.inputs.c03replicasLX == ''
        run: |
            c02replicasLX="rahul"
            c03replicasLX="reddy"
            echo "c02replicasLX=${c02replicasLX}" >> $GITHUB_ENV
            echo "c03replicasLX=${c03replicasLX}" >> $GITHUB_ENV

      - name: show the var output
        run: |
            echo "hi ${{ env.c02replicasLX }} ${{ env.c03replicasLX }}"
          
          
 


      
