name: dns_records
on:
  workflow_dispatch:
    inputs:
      C01-replicasLX:
        type: choice
        description: 'cluster C01 LX Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
      C02-replicasLX:
        type: choice
        description: 'cluster C02 LX Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"        
      clusters_list:
        type: string
        description: 'list of clusters'
        required: true
        default: 'c01,c02'
env:
  NAMESPACES: 'dev,qa,stg'
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:
      - name: Get MongoDB Dump
        run: |
          declare -A clusters
          clusters[c01]=${{ inputs.C01-replicasLX }}
          clusters[c02]=${{ inputs.C02-replicasLX }}
          for i in "${clusters[@]}"
          do
              echo "c01 count: ${clusters[c01]}"
              echo "c02 count: ${clusters[c02]}"
          done
          
          
 


      
