name: dns_records
on:
  workflow_dispatch:
    inputs:
      Storge_size:
        type: string
        description: 'Provide the new storage size e.g: 80Gi'
        required: true
        default: '60Gi'
      days:
        type: string
        required: true
        default: '5'
        
      collections_list:
        type: string
        description: 'Enter list of collections to be excluded from mongodump separated by ",". ex: bridg-rule,age-limitation-mappings,addendum-summaries'
        required: true
        default: ''
env:
  NAMESPACES: 'dev,qa,stg'
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          path: skynet
          
      - name: Get MongoDB Dump
        run: |
          IFS="," read -a myarray <<< ${{ inputs.collections_list }}
          updated_excludelist=''
          for collection in "${myarray[@]}"; do
              excludelist="@--excludeCollection="$collection
              updated_excludelist=$updated_excludelist$excludelist
          done
          echo $updated_excludelist

      
