name: dns_records
on:
  workflow_dispatch:
    inputs:
      c01-replicasLX:
        type: choice
        description: 'cluster C01 LX Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
env:
  NAMESPACES: 'dev,qa,stg'
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:
      - name: declare lxkdbmc01
        run: |
          declare -A svc_ip_lxbdmc01
          START=3
          prevCount=1
          for i in $(eval echo "{$START..$prevCount}")
          do
            SVC_IP=10.96.1.$i
            HOSTNAME=lxkdbmc01-$i.lxkdbmc01-svc.cluster.local
            svc_ip_lxbdmc01+=( [$HOSTNAME]=$SVC_IP)
          done
          echo "svc_ip_lxbdmc01=${svc_ip_lxbdmc01}" >> $GITHUB_ENV
          
      - name: declare lxkdbmc02
        run: |
          declare -A svc_ip_lxbdmc02
          START=4
          prevCount=2
          for i in $(eval echo "{$START..$prevCount}")
          do
            SVC_IP=10.96.3.$i
            HOSTNAME=lxkdbmc02-$i.lxkdbmc02-svc.cluster.local
            svc_ip_lxbdmc02+=( [$HOSTNAME]=$SVC_IP)
          done
          if [ ${#svc_ip_lxbdmc01[@]} -ne 0 ]; then
            for key in ${!svc_ip_lxbdmc01[@]}; do
              echo ${key} ${svc_ip_lxbdmc01[${key}]}
            done
          else
            echo "All are empty"
          fi
        shell: bash
          
          
 


      
