name: dns_records
on:
  workflow_dispatch:
    inputs:
      C01-replicasVW:
        type: choice
        description: 'cluster C01 VW Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"        
      clusters_list:
        type: string
        description: 'list of clusters'
        required: true
        default: 'c01,c02'
env:
  NAMESPACES: 'dev,qa,stg'
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          path: skynet
          
      - name: Get MongoDB Dump
        run: |
          START=1
          END=${{ inputs.C01-replicasVW }}
          IFS=',' read -r -a array <<< ${{ inputs.clusters_list }}
          for i in "${array[@]}"
          do
            for j in $(eval echo "{$START..$END}")
            do
              inst=$((j-1))
              echo $i$inst
            done
          done
          
 


      
