name: dns_records
on:
  workflow_dispatch:
    inputs:
      c01-replicasLX:
        type: choice
        description: 'cluster C01 LX Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
      C02-replicasLX:
        type: choice
        description: 'cluster C02 LX Replicas count'
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"        
      clusters_list:
        type: string
        description: 'list of clusters'
        required: true
        default: 'c01,c02'
env:
  NAMESPACES: 'dev,qa,stg'
jobs:
  dns_records:
    runs-on: ubuntu-latest
    steps:
      - name: Get MongoDB Dump
        run: |
          declare -A arr
        shell: bash
          
          
 


      
