name: MongoDB-Deploy-Additional-Pods
on:
  workflow_dispatch:
    inputs:
      dbpathStorage:
        type: choice
        description: 'Storage'
        options:
        - 50Gi
        - 60Gi
        - 70Gi
        - 80Gi
        - 90Gi
        - 100Gi
        - 200Gi
        - 2800Gi

jobs:
  additional-pods:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Create Configmap
        run: |
          echo "hello"
          ls -al

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: vasuenduri/infra-helm-repo
          token: "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"
          path: infra-helm-repo
          

