name: MongoDB-Deploy-Additional-Pods
on:
  workflow_dispatch:
    inputs:
      dbpathStorage:
        type: choice
        description: 'Storage'
        options:
        - 50Gi
        - 60Gi
        - 70Gi
        - 80Gi
        - 90Gi
        - 100Gi
        - 200Gi
        - 2800Gi

jobs:
  additional-pods:
    runs-on: ubuntu-latest
    steps:
      - name: Clear submodule if it exists and remove binaries if exists.
        run: |
          # Print out info about the current directory
          pwd
          ls -l
          # Remove the problematic submodule if it exists
          rm -rf ./skynet-mongodb/skynet-mongodb
          
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          path: skynet

      - name: Create Configmap
        run: |
          echo "hello"
          ls -al
          rm -rf .git .github
          ls -al

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: vasuenduri/infra-helm-repo
          path: infra-helm-repo
          

