name: teja_test
on:
  workflow_dispatch:
    inputs:
      C01-replicasLX:
        type: choice
        description: 'cluster C01 LX Replicas count'
        options:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
env:
  NAMESPACES: 'dev,qa,stg'
jobs:
  teja_test:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          path: skynet
          
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'pip'
          
      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f skynet/requirements.txt ]; then pip install -r skynet/requirements.txt; fi
          
      
